### ISSUE TITLE
Are the graphs assumed to be undirected?

### ISSUE THREAD

**Issue by ghuryejay** [iwiwi/pruned-landmark-labeling#1]
Hi,

DO you assume that the graphs are undirected for the shortest path computation? For example, if I give (1-->2) as a link then will (2 --> 1) be added by default to the graph? If yes, then is there any way to avoid that?

Thanks.

**Comment by ghuryejay** [comment]
Ping!

**Comment by iwiwi** [comment]
This implementation assume that the given graph is undirected.

Here is our implementation for directed graph, I hope this will help :) 
https://github.com/iwiwi/agl/blob/master/src/shortest_path/dynamic_pruned_landmark_labeling.h
