### ISSUE TITLE
Unable to Run Programme

### ISSUE THREAD

**Issue by sanyamnn** [iwiwi/pruned-landmark-labeling#2]
I am unable to run the programme , on my mac ,on running "make" , in cloned directory, terminal displays the following  error : 
"g++ -g -Wall -Wextra -O3 -Isrc -o bin/construct_index samples/construct_index_main.cc src/pruned_landmark_labeling.h
clang: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang: error: cannot specify -o when generating multiple output files
make: *** [bin/construct_index] Error 1"

**Comment by mhnamaki** [comment]
I could run the program on Linux but were unable also to run it on Mac.

**Comment by ekstroem** [comment]
I'm having the same problem - again on a mac. Did anyone find a  fix for this?

**Comment by sanyamnn** [comment]
Yes , I was able to find a solution to this .
I read the "makefile" documentation and found that it couldn't be executed on UNIX Operating Systems like Macintosh .
You need to go compulsorily for any linux for executing this programme .
It worked fluently on Ubuntu and Kali Linux , for me.

**Comment by mhnamaki** [comment]
Dear all,
I could run the program on Mac. However, following changes need to be made (at least for me):

comment these:
//#include <malloc/malloc.h>
//#include <xmmintrin.h>

Then everywhere it has memalign =>
//index_ = (index_t*)//memalign(64, V * sizeof(index_t));
posix_memalign((void **) &index_, 64, V * sizeof(index_t));

Comment these:
// Prefetch
 //  _mm_prefetch(&idx_v.bpspt_d[0], _MM_HINT_T0);
  // _mm_prefetch(&idx_v.bpspt_s[0][0], _MM_HINT_T0);
 // _mm_prefetch(&tmp_idx_v.first[0], _MM_HINT_T0);
//_mm_prefetch(&tmp_idx_v.second[0], _MM_HINT_T0);
 // _mm_prefetch(&idx_v.spt_v[0], _MM_HINT_T0);
    // _mm_prefetch(&idx_w.spt_v[0], _MM_HINT_T0);
    //_mm_prefetch(&idx_v.spt_d[0], _MM_HINT_T0);
    // _mm_prefetch(&idx_w.spt_d[0], _MM_HINT_T0);

Good luck :).
